// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > types/supabase.ts
// Placeholder for now
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]
